### ISSUE TITLE
Add metadata for cohort 'admin'

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#120]
As per @matentzn request, would it be possible to expand the cohort metadata to include the fields at https://ihccglobal.org/membercohorts/? Fields should be optional.

in addition to the existing 

Cohort ID
Title
Description
License
Rights

Also, do we need both License and Rights?

**Comment by jamesaoverton** [comment]
@matentzn is working on this. License and rights were discussed here: https://github.com/IHCC-cohorts/data-harmonization/issues/3#issuecomment-595808865

**Comment by matentzn** [comment]
@mcourtot Since IHCC seems to have all this metadata already - shouldn't we be using that rather than asking the *data dictionary maintainers* again for all these? These seem to be all:

- Cohort Name (that is our "Title")
- PI/Lead
- Regions
- Enroll Start
- Enroll End
- Enrolled
- Target Enrollment
- Genomic Data
- Env. Data
- Bio specimens
- Phenotypic Data
- Data Sharing
- Date Verified

So when we are saying "add cohort metadata", I initially understood: "add as field in the metadata template, to be filled out by the data dictionary maintainer". Did you maybe mean: "add all these metadata fields that we already have in our database to the OWL version of the data dictionary?"

**Comment by mcourtot** [comment]
I think it's about adding them to the template and the ontology, rather than filling the values in - you are right they should be optional, and for those cohorts for which we already have the info we should be able to pull it (though at the moment this is csv powered for ihcc afaik) New cohorts will fill the values in.

**Comment by matentzn** [comment]
We can easily add these optional fields, but it seems like we would be duplicating the gathering of this information if the process that does it for https://ihccglobal.org/membercohorts/ does exactly the same? Wouldnt it be better to have one central process gathering this information, and not two disconnected ones? I was under the assumption that the data harmonization stuff was only about the mappings, and that the set of mapped data dictionaries will always be a subset of https://ihccglobal.org/membercohorts/. Is that a wrong assumption?

**Comment by mcourtot** [comment]
We discussed capturing this to serve as source of truth for the IHCC website and others.

Helen Parkinson points to https://web.www.healthdatagateway.org/search?search=cohort&tab=Datasets as well as possible source of inspiration

**Comment by mcourtot** [comment]
Could we push this up please? We are talking with other cohorts to make a generic model for admin data and would like this to be shared.

**Comment by jamesaoverton** [comment]
We are capturing this data in the current template: https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/ihcc-data-dictionary-registration-template.xlsx

**Comment by mcourtot** [comment]
Should those fields be added to the GECKO? Maybe not the type of specimens as this should be derived from the dictionary itself, but the rest?

**Comment by beckyjackson** [comment]
I think that the original issue here is resolved since these fields are in the registration template. @mcourtot is your last comment suggesting to add the metadata fields to GECKO? Can we open a separate issue for that?
