### ISSUE TITLE
Generate OWL file for Maelstrom

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#5]
- [x] Copy <https://github.com/maelstrom-research/maelstrom-taxonomies/blob/master/AreaOfInformation.yml> to `data/maelstrom.yml`
- [x] Update `data/README.md`
- [x] Create `src/maelstrom.py` script to generate a basic `build/maelstrom.tsv` ROBOT template
- [x] Create `metadata/maelstrom.ttl`, note the CC-by-nc-nd license
- [x] Update `Makefile` to build `build/maelstrom.owl` from the template and metadata

**Comment by mcourtot** [comment]
I went to check the CC license content and information about what constitutes a derivative work. 
1. [This document ](https://mollykleinman.com/2008/10/20/cc-howto-no-derivatives/) states "A derivative work involves enough creativity and originality that it constitutes a new copyrightable work. Simply converting a work from one medium to another — from print to digital, or CD to MP3 — does not produce a derivative work."
2. The [text of the license](https://creativecommons.org/licenses/by-nc-nd/2.5/legalcode) states (emphasis mine):
"3. License Grant. Subject to the terms and conditions of this License, Licensor hereby grants You a worldwide, royalty-free, non-exclusive, perpetual (for the duration of the applicable copyright) license to exercise the rights in the Work as stated below:
to reproduce the Work, to incorporate the Work into one or more Collective Works, and to reproduce the Work as incorporated in the Collective Works;
to distribute copies or phonorecords of, display publicly, perform publicly, and perform publicly by means of a digital audio transmission the Work including as incorporated in Collective Works;
The above rights may be exercised in all media and formats whether now known or hereafter devised. **The above rights include the right to make such modifications as are technically necessary to exercise the rights in other media and formats**, but otherwise you have no rights to make Derivative Works."

My interpretation is therefore that a format conversion is permitted under the terms of the [Maelstrom license](https://github.com/maelstrom-research/maelstrom-taxonomies/commit/0d023a3d31280a0a444a8bc1de07081a828caead). However I am checking with the Maelstrom PI whether this is correct and matches their expectations. Please hold off in the meantime.

**Comment by jamesaoverton** [comment]
The code is ready to go, but we haven't had a clear answer about the license.

**Comment by mcourtot** [comment]
Isabel confirmed they were happy for us to use Maelstrom. They will work on updating the licence. In the meantime we can proceed with conversion to OWL as per above. We will only refer to it from GECKO at the moment until the licence is updated.

**Comment by mcourtot** [comment]
Can we please add this to the OLS load? thanks!

**Comment by jamesaoverton** [comment]
Done: http://193.62.55.169:8080/ontologies/maelstrom
